name: Create Roles

on:
  workflow_dispatch:

jobs:
  assignment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_ROLE_ASSIGNMENT }}

      - name: Assign Key Vault RBAC Role
        shell: pwsh
        run: ./scripts/assign_roles.ps1 `
              -KeyVaultName "kv-taskGen-2" `
              -AppServiceName "app-service-taskGen-dev" `
              -ResourceGroup "rg-taskGen-dev-weu"
