name: Assign Key Vault RBAC Role

on:
  workflow_dispatch:

jobs:
  assign-keyvault-role:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_ROLE_ASSIGNMENT }}

      - name: Assign Key Vault RBAC Role
        run: |
          # Variables
          KEYVAULT_NAME="kv-taskGen-2"
          RESOURCE_GROUP="rg-taskGen-dev-weu"
          SP_IDENTIFIER="github-actions-sp3"  # Can also use SP AppId

          # Get Key Vault resource ID
          KV_ID=$(az keyvault show \
            --name $KEYVAULT_NAME \
            --resource-group $RESOURCE_GROUP \
            --query id -o tsv)

          echo "Key Vault Resource ID: $KV_ID"

          # Assign 'Key Vault Secrets User' role to the SP
          az role assignment create \
            --assignee $SP_IDENTIFIER \
            --role "Key Vault Secrets User" \
            --scope $KV_ID

        shell: bash
